/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as FounderToLaunchFrameworkRouteImport } from './routes/founder-to-launch-framework'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderToLaunchFrameworkRoute =
  FounderToLaunchFrameworkRouteImport.update({
    id: '/founder-to-launch-framework',
    path: '/founder-to-launch-framework',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/founder-to-launch-framework': typeof FounderToLaunchFrameworkRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/founder-to-launch-framework': typeof FounderToLaunchFrameworkRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/founder-to-launch-framework': typeof FounderToLaunchFrameworkRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blueprint'
    | '/contact'
    | '/founder-to-launch-framework'
    | '/resume'
    | '/services'
    | '/admin/blog'
    | '/admin/login'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blueprint'
    | '/contact'
    | '/founder-to-launch-framework'
    | '/resume'
    | '/services'
    | '/admin/blog'
    | '/admin/login'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blueprint'
    | '/contact'
    | '/founder-to-launch-framework'
    | '/resume'
    | '/services'
    | '/admin/blog'
    | '/admin/login'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlueprintRoute: typeof BlueprintRoute
  ContactRoute: typeof ContactRoute
  FounderToLaunchFrameworkRoute: typeof FounderToLaunchFrameworkRoute
  ResumeRoute: typeof ResumeRoute
  ServicesRoute: typeof ServicesRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-to-launch-framework': {
      id: '/founder-to-launch-framework'
      path: '/founder-to-launch-framework'
      fullPath: '/founder-to-launch-framework'
      preLoaderRoute: typeof FounderToLaunchFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlueprintRoute: BlueprintRoute,
  ContactRoute: ContactRoute,
  FounderToLaunchFrameworkRoute: FounderToLaunchFrameworkRoute,
  ResumeRoute: ResumeRoute,
  ServicesRoute: ServicesRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
